### ISSUE TITLE
Review: JS Advanced. Prototype & OOP

### ISSUE THREAD

**Issue by AlekseiIvshin** [marselkhisamov/EPAMtraining#2]
Task1 - 1
Task2 - 0 - Надо следовать контракту при переопределении методов (toString & valueOf)
Task3 - 0 - 
- MonsterTruck - "открывает" сразу; 
- Наследование предполагает, что проверка instanceof со всеми родительскими классами будет возвращать true. Например, `new MonsterTruck() instanceof Vehical -> true`

Task4 - 2

**Итоговая оценка 0**

**Comment by marselkhisamov** [comment]
@AlekseiIvshin 
**Task2 переопределил методы. Например для MonsterTruck:**

this.toString = function(){
    var monstStr = "speed: " + this.speed + ", wheelsCount: " + this.wheelsCount +
     ", doorsCount: " + this.doorsCount + ", openDoors: " + this.openDoors +
      ", closeDoors: " + this.closeDoors + ", wheelSize: " + this.wheelSize;
  return console.log(monstStr);
  }
  this.valueOf = function(){
     return console.log(this.wheelSize);
  }

**Task3 Переделал таймаут**

var open = this.openDoor
  this.openDoor = function (){
    setTimeout(open.bind(this),1000)
  }

**Как в прототипном наследовании добавил для всех классов:**

Bike.prototype = Object.create(Vehical.prototype);
Bike.prototype.constructor = Bike;
Car.prototype = Object.create(Vehical.prototype);
Car.prototype.constructor = Car; 
MonsterTruck.prototype = Object.create(Car.prototype);
MonsterTruck.prototype.constructor = MonsterTruck;

**Comment by AlekseiIvshin** [comment]
**Task2** - Неправильно, тк `toString` и `valueOf` должны возвращать строки и число соответственно([доки](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Object/toString)). Что они возвращают в твоем примере?

```
this.valueOf = function(){
return console.log(this.wheelSize);
}
```

**Comment by AlekseiIvshin** [comment]
Task1 - 1
Task2 - 1
Task3 - 1
Task4 - 2

**Итоговая оценка 2**
